### ISSUE TITLE
Some questions about the config files.

### ISSUE THREAD

**Issue by hunterhector** [pxch/event_imp_arg#1]
I am trying to run some scripts to get the evaluation files. However, I couldn't find documentation for a couple of settings. For example, there are two files missing: 

1. file name of propositions in Nombank corpus 
2. file name of noun list in Nombank corpus

https://github.com/pxch/event_imp_arg/blob/master/src/config.py#L35

I suppose they are simple files like a list of nouns, but I didn't know the format of these files.

**Comment by pxch** [comment]
'nombank.1.0.words' is just a list of all noun words in the NomBank annotation, and should come with the NomBank distribution.

'nombank.1.0_sorted_old' is a sorted version of 'nombank.1.0' for fast indexing, and 'nombank.1.0' should also come with the NomBank distribution. I believe you should be able to get exactly same results by using just 'nombank.1.0' (might be slower).

You can download the zip file from https://nlp.cs.nyu.edu/meyers/NomBank.html

**Comment by hunterhector** [comment]
I see, it seems like I am using a version of NomBank from LDC, which does not contain these files. The data from your link contains the correct files. Thanks. 

By the way, the vocabulary files [1] can only be obtained after process the Wikipedia data, right? 

[1] https://github.com/pxch/event_imp_arg/blob/master/src/config.py#L68

**Comment by pxch** [comment]
Yes that's correct.
